import os
import sys
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()

# Add parent directory to path so we can import logger
sys.path.insert(0, str(Path(__file__).parent.parent))

from langchain.agents import create_agent
from langchain.chat_models import init_chat_model
from langchain.tools import tool
from langchain_openai import OpenAIEmbeddings
from langchain_pinecone import PineconeVectorStore
from langchain_core.messages import ToolMessage

from logger import log_error, log_info, log_success


# embeddings:
embeddings = OpenAIEmbeddings(api_key=os.environ["OPENAI_API_KEY"], model="text-embedding-3-small")

# vector store:
vector_store = PineconeVectorStore(index_name=os.environ["PINECONE_INDEX_NAME"], embedding=embeddings)

# creating chat model:
model = init_chat_model(model="gpt-5-nano", model_provider='openai')

# tools:
@tool(response_format="content_and_artifact") # this is a custom response format that indicates the tool will return both content (the retrieved documents) and an artifact (metadata about the retrieval, like sources or relevance scores).
def retrieve_from_vector_store(query: str):
    """Tool to retrieve relevant documents about langchain from the vector store."""
    try:
        results = vector_store.as_retriever().invoke(query, k=4) # as_retriever() converts the vector store into a retriever interface that can be used to fetch relevant documents based on a query. k=4 means we want to retrieve the top 4 most relevant documents for the given query.
        # as_retriever is better than similarity_search because it can handle more complex retrieval logic and can be more efficient for large datasets, while similarity_search is a simpler method that retrieves documents based on cosine similarity of embeddings, which may not always yield the best results for complex queries.
        # also on langsmith we have optimized the retriever to be more efficient and effective, so using as_retriever allows us to take advantage of those optimizations.
        log_success(f"Tool: Successfully retrieved {len(results)} relevant documents for query: '{query}'")

        # serialize the documents:
        serialized = f"\n\n".join((f"Source: {doc.metadata.get('source', 'Unknown')}\n\nContent: {doc.page_content}" for doc in results))
        return serialized, results  # return both the serialized content and the original documents as an artifact for potential further use (like citing sources in the agent's response)
    except Exception as e:
        log_error(f"Tool: Error retrieving documents for query: '{query}' - {str(e)}")
        return []  # Return empty list on error to allow the agent to continue functioning


# llm agent:
def run_llm(query):
    """Run the RAG pipeline to answer a user query using retrieved documents.
        Args:
            query: The user's question or prompt that we want to answer using the RAG pipeline.
        Returns:
            Dictionary containing:
                - answer: The final answer generated by the LLM after processing the retrieved documents.
                - context: The list of documents that were retrieved from the vector store and used to generate the answer.
    """
    system_prompt = """You are a helpful assistant that answers questions about LangChain. 
                    Use the retrieved documents to provide accurate and concise answers. 
                    Always cite your sources from the retrieved documents in your response.
                    If you don't know the answer, say you don't know. Do not make up answers."""
    try:
        # creating the agent:
        agent = create_agent(model=model, tools=[retrieve_from_vector_store], system_prompt=system_prompt)

        # building the messages:
        messages = [
            {"role": "user", "content": query}
        ]

        # running the agent:
        response = agent.invoke({"messages": messages})

        # extract the answer from last AI message:
        answer = response["messages"][-1].content

        # extract the retrieved documents from the tool calls:
        context_docs = []
        for message in response["messages"]:
            if isinstance(message, ToolMessage) and hasattr(message, "artifact"):
                if isinstance(message.artifact, list):  # check if artifact is a list of documents, this is needed because the tool returns both a serialized string and the original documents as an artifact, we want to make sure we only process the original documents.
                    context_docs.extend(message.artifact)
        log_success(f"LLM Agent: Successfully generated answer for query: '{query}'")
        return {"answer": answer, "context": context_docs}
    except Exception as e:
        log_error(f"LLM Agent: Error generating answer for query: '{query}' - {str(e)}")
        return {"answer": "Sorry, I encountered an error while trying to answer your question.", "context": []}
    

# main function:
if __name__ == "__main__":
    user_query = "What are deep agents ?"
    result = run_llm(user_query)
    print("Answer:", result["answer"])
    print("\nRetrieved Documents:")
    for doc in result["context"]:
        print(f"- Source: {doc.metadata.get('source', 'Unknown')}")
        print(f"  Content: {doc.page_content[:200]}...")  # printing only the first 200 characters of each document for brevity
